=== EmanueleDeSantis/LockscreenEar/app/src/main/assets/notes_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="notes_list">
		<xs:complexType>
			<xs:sequence>
  				<xs:element ref="note" minOccurs="42" maxOccurs="42" />
  			</xs:sequence>
  		</xs:complexType>
  	</xs:element>
  	<xs:element name="note">
  		<xs:complexType>
			<xs:sequence>
  				<xs:element ref="name" />
  				<xs:element ref="sound_name" />
  			</xs:sequence>
  			<xs:attribute name="id" use="required">
  				<xs:simpleType>
  					<xs:restriction base="xs:positiveInteger">
  						<xs:minInclusive value="1" />
  						<xs:maxInclusive value="42" />
  					</xs:restriction>
  				</xs:simpleType>
  			</xs:attribute>
  		</xs:complexType>
  	</xs:element>
  	<xs:element name="name" type="xs:string" />
  	<xs:element name="sound_name" type="xs:string" />
</xs:schema>

=== EmanueleDeSantis/LockscreenEar/app/src/main/assets/notes.xml
<?xml version="1.0" encoding="UTF-8"?>
<notes_list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="notes_schema.xsd">
	<note id="1">
		<name>sol</name>
		<sound_name>sol2</sound_name>
	</note>
	<note id="2">
		<name>soldie</name>
		<sound_name>soldie2</sound_name>
	</note>
	<note id="3">
		<name>la</name>
		<sound_name>la2</sound_name>
	</note>
	<note id="4">
		<name>ladie</name>
		<sound_name>ladie2</sound_name>
	</note>
	<note id="5">
		<name>si</name>
		<sound_name>si2</sound_name>
	</note>
	<note id="6">
		<name>do</name>
		<sound_name>do3</sound_name>
	</note>
	<note id="7">
		<name>dodie</name>
		<sound_name>dodie3</sound_name>
	</note>
	<note id="8">
		<name>re</name>
		<sound_name>re3</sound_name>
	</note>
	<note id="9">
		<name>redie</name>
		<sound_name>redie3</sound_name>
	</note>
	<note id="10">
		<name>mi</name>
		<sound_name>mi3</sound_name>
	</note>
	<note id="11">
		<name>fa</name>
		<sound_name>fa3</sound_name>
	</note>
	<note id="12">
		<name>fadie</name>
		<sound_name>fadie3</sound_name>
	</note>
	<note id="13">
		<name>sol</name>
		<sound_name>sol3</sound_name>
	</note>
	<note id="14">
		<name>soldie</name>
		<sound_name>soldie3</sound_name>
	</note>
	<note id="15">
		<name>la</name>
		<sound_name>la3</sound_name>
	</note>
	<note id="16">
		<name>ladie</name>
		<sound_name>ladie3</sound_name>
	</note>
	<note id="17">
		<name>si</name>
		<sound_name>si3</sound_name>
	</note>
	<note id="18">
		<name>do</name>
		<sound_name>do4</sound_name>
	</note>
	<note id="19">
		<name>dodie</name>
		<sound_name>dodie4</sound_name>
	</note>
	<note id="20">
		<name>re</name>
		<sound_name>re4</sound_name>
	</note>
	<note id="21">
		<name>redie</name>
		<sound_name>redie4</sound_name>
	</note>
	<note id="22">
		<name>mi</name>
		<sound_name>mi4</sound_name>
	</note>
	<note id="23">
		<name>fa</name>
		<sound_name>fa4</sound_name>
	</note>
	<note id="24">
		<name>fadie</name>
		<sound_name>fadie4</sound_name>
	</note>
	<note id="25">
		<name>sol</name>
		<sound_name>sol4</sound_name>
	</note>
	<note id="26">
		<name>soldie</name>
		<sound_name>soldie4</sound_name>
	</note>
	<note id="27">
		<name>la</name>
		<sound_name>la4</sound_name>
	</note>
	<note id="28">
		<name>ladie</name>
		<sound_name>ladie4</sound_name>
	</note>
	<note id="29">
		<name>si</name>
		<sound_name>si4</sound_name>
	</note>
	<note id="30">
		<name>do</name>
		<sound_name>do5</sound_name>
	</note>
	<note id="31">
		<name>dodie</name>
		<sound_name>dodie5</sound_name>
	</note>
	<note id="32">
		<name>re</name>
		<sound_name>re5</sound_name>
	</note>
	<note id="33">
		<name>redie</name>
		<sound_name>redie5</sound_name>
	</note>
	<note id="34">
		<name>mi</name>
		<sound_name>mi5</sound_name>
	</note>
	<note id="35">
		<name>fa</name>
		<sound_name>fa5</sound_name>
	</note>
	<note id="36">
		<name>fadie</name>
		<sound_name>fadie5</sound_name>
	</note>
	<note id="37">
		<name>sol</name>
		<sound_name>sol5</sound_name>
	</note>
	<note id="38">
		<name>soldie</name>
		<sound_name>soldie5</sound_name>
	</note>
	<note id="39">
		<name>la</name>
		<sound_name>la5</sound_name>
	</note>
	<note id="40">
		<name>ladie</name>
		<sound_name>ladie5</sound_name>
	</note>
	<note id="41">
		<name>si</name>
		<sound_name>si5</sound_name>
	</note>
	<note id="42">
		<name>do</name>
		<sound_name>do6</sound_name>
	</note>
</notes_list>
